codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1
    wait_for_ci: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: success
    patch:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: success

comment:
  layout: "reach, diff, flags, files"
  require_changes: false
  behavior: default

ignore:
  - "**/*.md"
  - "**/dist/**"
  - "**/build/**"
  - "**/node_modules/**"
  - "**/*.config.*"
